spring:
  config:
    import: optional:classpath:secret.properties
  application:
    name: muncher

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver

app:
  messaging:
    exchange: offers
    routing-key: collected
    queue: offers.collected

logging:
  file:
    name: ../logs/muncher.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"
  level:
    root: info