spring:
  config:
    import: optional:classpath:secret.properties
  application:
    name: muncher
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver

app:
  messaging:
    exchange: offers
    routing-key: collected
    queue: offers.collected